// Generated by Wrangler on Tue Jun 04 2024 09:34:52 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	API_URL: "https://hnai-server.lakshb.workers.dev/";
}
